<?php

include("dbConnection.php");

use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\Exception;


if (isset($_POST['email_data'])) {
    // require 'PHPMailer-master/src/Exception.php';
    require '../PHPMailer-master/src/Exception.php';
    require '../PHPMailer-master/src/PHPMailer.php';
    require '../PHPMailer-master/src/SMTP.php';
    $output = '';

    foreach ($_POST['email_data'] as $row) {

        // $rcpnric = $row['rcpnric'];
        $rcpid = $row['rcpid'];
        $sql = "SELECT * FROM certificate INNER JOIN recipient ON recipient.s_id=certificate.rcp_id INNER JOIN event ON event.eventID=recipient.s_eventID WHERE certificate.rcp_id='$rcpid'";
        $result = $conn->query($sql);

        if ($result->num_rows > 0) {
            while ($row = mysqli_fetch_array($result)) {

                $cert_id = $row['cert_id'];
                $email = $row['s_email'];
                $name = $row['s_name'];
                $event_name = $row['eventName'];

                $cert_path = "../assets/images/certificate/$cert_id.png";

                $mail = new PHPMailer;
                $mail->isSMTP();
                $mail->Host = "smtp.gmail.com"; //smtp.domain.com
                $mail->Port = 587;
                $mail->SMTPSecure = "tls";
                $mail->SMTPAuth = true;
                $mail->Username = "psmdcms@gmail.com"; //Sender username
                $mail->Password = "psmdcms2021"; //Sender email password
                $mail->setFrom("psmdcms@gmail.com"); //Sender email
                // $mail->FromName = "i-Cert"; //Sender name that will view by recipient
                $mail->addAddress($email, $name);
                $mail->isHTML(true);
                $mail->Subject = "Certificate Generated by DCMS";
                $mail->Body = "<h2>Dear " . $name . ",</h2><br><h4>Thank you so much for participating in the " . $event_name . " program. Congratulations for the certificate.<br>Attached your certificate in PNG format.</h4>";
                $mail->addAttachment($cert_path); //Cert as attachment
                $mail->SMTPOptions = array("ssl" => array(
                    "verify_peer" => false,
                    "verify_peer_name" => false,
                    "verify_self_signed" => false,

                ));

                $status = $mail->Send();
                if ($status["code"] == '400') {
                    $output .= html_entity_decode($status['full_error']);
                }
            }
        }
    }

    if ($output == '') {
        echo 'Okay';
    } else {
        echo $output;
    }
}
